In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'1.2.4'

In [3]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [4]:
df=pd.DataFrame(arr,index=["A","B","C"],columns=["col1","col2","col3","col4"])
df

   col1  col2  col3  col4
A     1     2     3     4
B     5     6     7     8
C     9    10    11    12

In [5]:
mydict={"col1":[1,5,9],"col2":[2,6,10],"col3":[3,7,11],"col4":[4,8,12]}
df1=pd.DataFrame(mydict,index=["A","B","C"])
df1

   col1  col2  col3  col4
A     1     2     3     4
B     5     6     7     8
C     9    10    11    12

In [6]:
df.loc["A","col2"]

2

In [7]:
df.iloc[0,3]

4

In [8]:
df.loc[["A","B"],"col2"]

A    2
B    6
Name: col2, dtype: int32

In [9]:
df.iloc[:,3]

A     4
B     8
C    12
Name: col4, dtype: int32

In [10]:
df["col5"]=[8,88,888]
df

   col1  col2  col3  col4  col5
A     1     2     3     4     8
B     5     6     7     8    88
C     9    10    11    12   888

In [11]:
df.loc["A","col3"]=0

In [12]:
df

   col1  col2  col3  col4  col5
A     1     2     0     4     8
B     5     6     7     8    88
C     9    10    11    12   888

In [13]:
df.dtypes

col1    int32
col2    int32
col3    int32
col4    int32
col5    int64
dtype: object

In [14]:
df["col1"]=["{:.2f}".format(float(x)) for x in df.iloc[:,0]]
df

   col1  col2  col3  col4  col5
A  1.00     2     0     4     8
B  5.00     6     7     8    88
C  9.00    10    11    12   888

In [15]:
#name=input("enter name")
#age=int(input("enter age"))
#avg=float(input("enter average"))
#print(f"my name is {name},Im{age}years old,my average is {avg:0.2f}")
#print("my name is {},Im{}years old,my average is {:0.2f}".format(name,age,avg))
#print(f"my name is %s,Im%dyears old,my average is %0.2f"%(name,age,avg))

In [16]:
#def func(a,b):
   # return a+b
#x,y=int(input("enter x")),int(input("enter y"))
#print(func(x,y))

In [17]:
#func=lambda a,b:a+b
#x,y=int(input("enter x")),int(input("enter y"))
#print(func(x,y))

In [18]:
df.col2=df["col2"].apply(lambda x:"{:.2f}".format(float(x)))
df

   col1   col2  col3  col4  col5
A  1.00   2.00     0     4     8
B  5.00   6.00     7     8    88
C  9.00  10.00    11    12   888

In [19]:
mydf=df.astype(float).applymap("{:.2f}".format)
mydf

   col1   col2   col3   col4    col5
A  1.00   2.00   0.00   4.00    8.00
B  5.00   6.00   7.00   8.00   88.00
C  9.00  10.00  11.00  12.00  888.00

In [20]:
df.drop("col4",axis=1,inplace=True)
df

   col1   col2  col3  col5
A  1.00   2.00     0     8
B  5.00   6.00     7    88
C  9.00  10.00    11   888

In [21]:
df.rename(columns={"col3":"column3"},inplace=True)
df

   col1   col2  column3  col5
A  1.00   2.00        0     8
B  5.00   6.00        7    88
C  9.00  10.00       11   888

In [22]:
df.replace(8,"arash",inplace=True)
df

   col1   col2  column3   col5
A  1.00   2.00        0  arash
B  5.00   6.00        7     88
C  9.00  10.00       11    888

In [ ]:
df.col1
df["col1"]
df