In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([0,1, 2, 3,0, 4,5, 6, 7, 8])

a=np.nonzero(a<3)
a

(array([0, 1, 2, 4], dtype=int64),)

In [3]:
pd.__version__

'1.2.4'

In [4]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [5]:
#dataframe
df=pd.DataFrame(arr,index=["A","B","C"],columns=["col1","col2","col3","col4"])
df

   col1  col2  col3  col4
A     1     2     3     4
B     5     6     7     8
C     9    10    11    12

In [6]:
mydict={"col1":[1,5,9],"col2":[2,6,10],"col3":[3,7,10],"col4":[5,2,8]}
df1=pd.DataFrame(mydict,index=["A","B","C"],columns=["col1","col2","col3","col4"])
df1

   col1  col2  col3  col4
A     1     2     3     5
B     5     6     7     2
C     9    10    10     8

In [7]:
df.loc["A"]["col2"]

#ورژن های جدید پایینی
df.loc["A","col2"]

2

In [8]:
df.iloc[0][3]


df.iloc[0,3]
#new version

4

In [9]:
df.loc[["A","B"],"col2"]

A    2
B    6
Name: col2, dtype: int32

In [10]:
df.iloc[:,3]

A     4
B     8
C    12
Name: col4, dtype: int32

In [11]:
df["col5"]=[8,88,888]
df

   col1  col2  col3  col4  col5
A     1     2     3     4     8
B     5     6     7     8    88
C     9    10    11    12   888

In [12]:
df.loc[:,"col3"]=5
df

   col1  col2  col3  col4  col5
A     1     2     5     4     8
B     5     6     5     8    88
C     9    10     5    12   888

In [13]:
df.dtypes

col1    int32
col2    int32
col3    int64
col4    int32
col5    int64
dtype: object

In [14]:
df.astype(float)

   col1  col2  col3  col4   col5
A   1.0   2.0   5.0   4.0    8.0
B   5.0   6.0   5.0   8.0   88.0
C   9.0  10.0   5.0  12.0  888.0

In [15]:
df.astype(float).round(2)

   col1  col2  col3  col4   col5
A   1.0   2.0   5.0   4.0    8.0
B   5.0   6.0   5.0   8.0   88.0
C   9.0  10.0   5.0  12.0  888.0

In [16]:
df["col1"]=["{:.2f}".format(float(x)) for x in df.iloc[:,0]]
df
#or df.col1

   col1  col2  col3  col4  col5
A  1.00     2     5     4     8
B  5.00     6     5     8    88
C  9.00    10     5    12   888

In [17]:
cols = ["col2"]
df[cols] = df[cols].apply(lambda x: x.astype(float).round(2))
df

   col1  col2  col3  col4  col5
A  1.00   2.0     5     4     8
B  5.00   6.0     5     8    88
C  9.00  10.0     5    12   888

In [18]:
mydf=df.astype(float).applymap("{:.2f}".format)
mydf
#on new version map

   col1   col2  col3   col4    col5
A  1.00   2.00  5.00   4.00    8.00
B  5.00   6.00  5.00   8.00   88.00
C  9.00  10.00  5.00  12.00  888.00

In [19]:
df.drop("B",axis=0,inplace=True)
df
#0 ofoghi,1 amodi

   col1  col2  col3  col4  col5
A  1.00   2.0     5     4     8
C  9.00  10.0     5    12   888

In [20]:
df.rename(columns={"col3":"column3"},inplace=True)
df
#inplace=True تغییرات رو اعمال میکنه

   col1  col2  column3  col4  col5
A  1.00   2.0        5     4     8
C  9.00  10.0        5    12   888

In [21]:
df.replace(5,"arash",inplace=True)
df

   col1  col2 column3  col4  col5
A  1.00   2.0   arash     4     8
C  9.00  10.0   arash    12   888

In [23]:
df.replace(5,"arash",inplace=True)
df

   col1  col2 column3  col4  col5
A  1.00   2.0   arash     4     8
C  9.00  10.0   arash    12   888

In [33]:
a=np.array([2,4,6,4,65,4])
s=pd.Series(a,index=["a","b","c","d","e","f"])
s

a     2
b     4
c     6
d     4
e    65
f     4
dtype: int32