In [1]:
import numpy as np
import pandas as pd
from numpy import sqrt

In [2]:
movies_df=pd.read_csv(r"C:\Users\Student\Desktop\movies.csv")
ratings_df=pd.read_csv(r"C:\Users\Student\Desktop\ratings.csv")

In [3]:
movies_df["year"]=movies_df.title.str.extract("(\(\d\d\d\d\))") #digits or (r"(\(\d{4}\))")
movies_df["year"]=movies_df.year.str.extract("(\d\d\d\d)") #or (r"(\d{4})")
movies_df["title"]=movies_df.title.str.replace("(\(\d\d\d\d\))","",regex=True) #tonone
movies_df["title"]=movies_df["title"].apply(lambda x:x.strip()) #removespacesifexist

In [4]:
movies_df.drop("genres",axis=1)
movies_df.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

In [5]:
ratings_df=ratings_df.drop("timestamp",axis=1)
ratings_df.head()

   userId  movieId  rating
0       1      169     2.5
1       1     2471     3.0
2       1    48516     5.0
3       2     2571     3.5
4       2   109487     4.0

In [6]:
userinput=[{"title":"Toy Story","rating":3.5},
          {"title":"Dracula: Dead and Loving It","rating":5},
          {"title":"Jumanji","rating":2},
          {"title":"Casino","rating":5},
          {"title":"Copycat","rating":3}]

In [7]:
inputmovies=pd.DataFrame(userinput)
inputmovies

                         title  rating
0                    Toy Story     3.5
1  Dracula: Dead and Loving It     5.0
2                      Jumanji     2.0
3                       Casino     5.0
4                      Copycat     3.0

In [8]:
inputId=movies_df[movies_df["title"].isin(inputmovies["title"].tolist())]
inputmovies=pd.merge(inputId,inputmovies,on="title",how="inner") #داخلی و روی
inputmovies

,movieId,title,genres,year,rating
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,3.5
1,2,Jumanji,Adventure|Children|Fantasy,1995,2.0
2,12,Dracula: Dead and Loving It,Comedy|Horror,1995,5.0
3,16,Casino,Crime|Drama,1995,5.0
4,22,Copycat,Crime|Drama|Horror|Mystery|Thriller,1995,3.0

In [10]:
usersubset=ratings_df[ratings_df["movieId"].isin(inputmovies["movieId"].tolist())]
usersubset.head()

     userId  movieId  rating
11        4       16     4.0
479      13        2     2.0
636      14       16     3.0
638      14       22     3.0
749      15        1     4.0

In [12]:
usersubsetgroup=usersubset.groupby(["userId"])

In [13]:
usersubsetgroup.get_group(1130)

        userId  movieId  rating
104167    1130        1     0.5
104168    1130        2     4.0
104171    1130       16     0.5
104174    1130       22     2.0

In [15]:
usersubsetgroup=sorted(usersubsetgroup,key=lambda x:len(x[1]),reverse=True)

In [16]:
usersubsetgroup[0:3]

[(815,
         userId  movieId  rating
  73747     815        1     4.5
  73748     815        2     3.0
  73755     815       12     1.5
  73757     815       16     4.0
  73762     815       22     2.0),
 (1824,
          userId  movieId  rating
  166834    1824        1     5.0
  166835    1824        2     2.0
  166839    1824       12     1.0
  166842    1824       16     2.0
  166846    1824       22     1.0),
 (3127,
          userId  movieId  rating
  286117    3127        1     5.0
  286118    3127        2     3.0
  286125    3127       12     1.0
  286128    3127       16     4.0
  286133    3127       22     2.0)]

In [17]:
usersubsetgroup=usersubsetgroup[0:100]

In [18]:
pearsoncorelationDict={}
for name, group in usersubsetgroup:
    group=group.sort_values(by="movieId")
    inputmovies=inputmovies.sort_values(by="movieId")
    nRating=len(group)
    temp_df=inputmovies[inputmovies["movieId"].isin(group["movieId"].tolist())]
    tempRatingList=temp_df["rating"].tolist()
    tempGroupList=group["rating"].tolist()
    sxx=sum([i**2 for i in tempRatingList])-pow(sum(tempRatingList),2)/float(nRating)
    syy=sum([i**2 for i in tempGroupList]-pow(sum(tempGroupList),2)/float(nRating))
    sxy=sum(i*y for i,j in zip(tempRatingList,tempGroupList))-sum(tempRatingList)*sum(tempGroupList)/float(nRating)
    if sxx!=0 and syy!=0:
        pearsoncorelationDict[name]=sxy/sqrt(sxx*syy)
    else:
        pearsoncorelationDict[name]=o
    #بقیشو بزنم از روی فایل یا ویدیو کلاس

SyntaxError: invalid syntax (2531736145.py, line 11)

In [ ]:
#چند خط اینجا هست بزنم همرو

In [19]:
topuser=pearsonDf.sort_values(by="similarityIndex",ascending=False)[0:50]

NameError: name 'pearsonDf' is not defined

In [ ]:
tempTopuserRating["weightRating"]=topuserRating.groupby("movieId").sum()[["similarityIndex","weightRating"]]
#this is not the end

In [ ]:
recomendation_df=pd.DataFrame()
recomendation_df["weighted_average recommendation score"]=tempTopuserRating["sum_weightRating"]/tempTopuserRating["sum_similarity"]

#ادامشو بزنم فایلو چک کنم