In [1]:
import numpy as np
import pandas as pd

In [2]:
movies_df=pd.read_csv(r"C:\Users\Student\Desktop\movies.csv")
ratings_df=pd.read_csv(r"C:\Users\Student\Desktop\ratings.csv")

In [3]:
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
movies_df["year"]=movies_df.title.str.extract("(\(\d\d\d\d\))") #digits or (r"(\(\d{4}\))")
movies_df["year"]=movies_df.year.str.extract("(\d\d\d\d)") #or (r"(\d{4})")
movies_df["title"]=movies_df.title.str.replace("(\(\d\d\d\d\))","",regex=True) #tonone
movies_df["title"]=movies_df["title"].apply(lambda x:x.strip()) #removespacesifexist

In [5]:
movies_df.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

In [6]:
movies_df["genres"]=movies_df.genres.str.split("|")
movies_df.head()

,movieId,title,genres,year
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995
2,3,Grumpier Old Men,"[Comedy, Romance]",1995
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",1995
4,5,Father of the Bride Part II,[Comedy],1995

In [7]:
moviewithgenres_df=movies_df.copy()
for index,row in movies_df.iterrows():
    for genre in row["genres"]:
        moviewithgenres_df.at[index,genre]=1
        
moviewithgenres_df=moviewithgenres_df.fillna(0)
moviewithgenres_df.head()

,movieId,title,genres,year,Adventure,Animation,Children,Comedy,Fantasy,Romance,...,Horror,Mystery,Sci-Fi,IMAX,Documentary,War,Musical,Western,Film-Noir,(no genres listed)
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,Grumpier Old Men,"[Comedy, Romance]",1995,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",1995,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Father of the Bride Part II,[Comedy],1995,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
ratings_df.head()

   userId  movieId  rating   timestamp
0       1      169     2.5  1204927694
1       1     2471     3.0  1204927438
2       1    48516     5.0  1204927435
3       2     2571     3.5  1436165433
4       2   109487     4.0  1436165496

In [9]:
ratings_df=ratings_df.drop("timestamp",axis=1)
ratings_df.head()

   userId  movieId  rating
0       1      169     2.5
1       1     2471     3.0
2       1    48516     5.0
3       2     2571     3.5
4       2   109487     4.0

In [16]:
userinput=[{"title":"Toy Story","rating":3.5},
          {"title":"Dracula: Dead and Loving It","rating":5},
          {"title":"Jumanji","rating":2},
          {"title":"Casino","rating":5},
          {"title":"Copycat","rating":3}]

In [17]:
inputmovies=pd.DataFrame(userinput)
inputmovies

                         title  rating
0                    Toy Story     3.5
1  Dracula: Dead and Loving It     5.0
2                      Jumanji     2.0
3                       Casino     5.0
4                      Copycat     3.0

In [18]:
inputId=movies_df[movies_df["title"].isin(inputmovies["title"].tolist())]
inputmovies=pd.merge(inputId,inputmovies,on="title",how="inner") #داخلی و روی
inputmovies

,movieId,title,genres,year,rating
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995,3.5
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995,2.0
2,12,Dracula: Dead and Loving It,"[Comedy, Horror]",1995,5.0
3,16,Casino,"[Crime, Drama]",1995,5.0
4,22,Copycat,"[Crime, Drama, Horror, Mystery, Thriller]",1995,3.0

In [19]:
inputmovies=inputmovies.drop(columns=["genres","year"])

In [20]:
usermovies=moviewithgenres_df[moviewithgenres_df["movieId"].isin(inputmovies["movieId"].tolist())]

In [21]:
usermovies

,movieId,title,genres,year,Adventure,Animation,Children,Comedy,Fantasy,Romance,...,Horror,Mystery,Sci-Fi,IMAX,Documentary,War,Musical,Western,Film-Noir,(no genres listed)
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,12,Dracula: Dead and Loving It,"[Comedy, Horror]",1995,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,16,Casino,"[Crime, Drama]",1995,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,22,Copycat,"[Crime, Drama, Horror, Mystery, Thriller]",1995,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
usermovies=usermovies.reset_index(drop=True)
userGenreTable=usermovies.drop(columns=["movieId","title","genres","year"])
userGenreTable

,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,Action,Crime,Thriller,Horror,Mystery,Sci-Fi,IMAX,Documentary,War,Musical,Western,Film-Noir,(no genres listed)
0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
inputmovies["rating"]

0    3.5
1    2.0
2    5.0
3    5.0
4    3.0
Name: rating, dtype: float64

In [25]:
userprofile=userGenreTable.transpose().dot(inputmovies["rating"])
userprofile

Adventure             5.5
Animation             3.5
Children              5.5
Comedy                8.5
Fantasy               5.5
Romance               0.0
Drama                 8.0
Action                0.0
Crime                 8.0
Thriller              3.0
Horror                8.0
Mystery               3.0
Sci-Fi                0.0
IMAX                  0.0
Documentary           0.0
War                   0.0
Musical               0.0
Western               0.0
Film-Noir             0.0
(no genres listed)    0.0
dtype: float64

In [26]:
genreTable=moviewithgenres_df.set_index(moviewithgenres_df["movieId"])
genreTable=genreTable(columns=["movieId","title","genres","year"])
genreTable.head()
#چک کنم با فایل یا ویدیو کلاس

TypeError: 'DataFrame' object is not callable

In [28]:
recomendationTable_df=((genreTable*userprofile).sum(axis=1)/(userprofile.sum())
recomendationTable_df.head()

SyntaxError: invalid syntax (2298229739.py, line 2)

In [ ]:
recomendationTable_df=recomendationTable_df.sort_values(ascendinf=False)
recomendationTable_df.head()

In [ ]:
movies_df.loc[movies_df["movieId"].isin]
#check this on file or class videos